apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auth-operator-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: auth-operator-role-cluster
subjects:
  - kind: ServiceAccount
    name: auth-operator
    namespace: auth-operator
