apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auth-operator-role-cluster
rules:
  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [zalando.org]
    resources: [kopfpeerings, clusterkopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [events.k8s.io]
    resources: [events]
    verbs: [create]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [iamauthenticator.k8s.aws]
    resources: [iamidentitymappings]
    verbs: [list, watch, patch, get]

  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, get, update, create, patch]

  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - patch
      - update